name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy'
        required: true
        type: environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Your deployment steps go here
